/** The recorded claim set (specs/seed-data.md): each row names the edge it exercises. Inputs are real posts unless marked synthetic. */
export const FIXTURE_SET: Array<{ slug: string; input: string; edge: string; source: string; chain?: string }> = [
  { slug: "pepe-aping", input: "Smart Money is aping $PEPE hard today 🐋", edge: "hero · Smart Money buying · 14 same-name tokens · SM idle for 24 h while on the table", source: "idea card phrasing of OKX Insight 2026-09-14 (PEPE smart money +307%)" },
  { slug: "vvv-sm-buying", input: "Smart Money is buying $VVV on Base — net inflows all week", edge: "CONFIRMED · SM net buying 24 h and 7 d, ≥ 3 wallets", source: "synthetic from the smart-money/netflow top rows, 2026-09-18 12:40 UTC" },
  { slug: "uni-whale-sold", input: "A whale sold 600,000 UNI tokens, valued at approximately $5.1 million.", edge: "whale selling · holders' balance change is the primary signal", source: "https://x.com/OnchainLens/status/2100824200957366630 · 2026-09-18" },
  { slug: "hype-whale-falconx", input: "Whale Deposits 440K $HYPE ($36M) into FalconX, Withdraws 12.25K $ETH ($30M)", edge: "whale selling · native coin → hyperevm home chain · deposit reads as selling", source: "Lookonchain 72984 · 2026-09-18" },
  { slug: "uni-sm-holding", input: "UNI has rallied 2.7-fold from its lows, with smart money logging gains of nearly 1000%.", edge: "holding claim · tgm/holders smart_money · 15-credit path", source: "Lookonchain 73026 → theblockbeats 367811 · 2026-09-18" },
  { slug: "ai-robinhood-chain", input: "Artificial Inu (AI) whale sells off holdings at a high price on Robinhood Chain, pushing the token price down over 12%", edge: "chain hint in the text · (TICKER) extraction · robinhood chain", source: "Lookonchain 72973 · 2026-09-18 (chain named explicitly)" },
  { slug: "meme-whale-position", input: "A whale built a $1.04 million position in MEME, claiming the top spot on the token's holder list.", edge: "no Whale-labelled wallet in the token → UNVERIFIABLE U-NOCLASS · not on the SM table", source: "https://x.com/lookonchain/status/2099323718443163694 · 2026-09-14" },
  { slug: "uni-sm-buying-after-rally", input: "Smart Money is buying $UNI after the 30% rally", edge: "price already moved (+30 % in 24 h) · small SM flow", source: "synthetic, phrased from Lookonchain 73026 · 2026-09-18" },
  { slug: "hype-sm-bought", input: "The 820 million unlocked on September 6 was silently absorbed, and Hyperliquid Strategies just bought another 29.65 million $HYPE", edge: "fresh wallets dominate · SM flat/negative · no subject keyword (default smart_money)", source: "OKX Orbit Insight 87337914594080 · 2026-09-14" },
  { slug: "xqzplm-unknown", input: "SM is loading $XQZPLM", edge: "no token by that name → UNVERIFIABLE U-TOKEN, 0 credits", source: "synthetic" },
  { slug: "pepe-not-a-flow-claim", input: "$PEPE will 10x after the listing 🚀", edge: "not a flow claim → UNVERIFIABLE U-CLAIM, 0 calls", source: "synthetic" },
  { slug: "edel-tweet-url", input: "https://x.com/lookonchain/status/2099673587125014572", edge: "x.com URL → oEmbed text → whale buying claim", source: "https://x.com/lookonchain/status/2099673587125014572 · 2026-09-15" },
  { slug: "zec-not-a-nansen-chain", input: "Zcash whales accumulate: three fresh wallets pull 28,759 $ZEC ($41.43M) from Binance and other exchanges", edge: "coin whose home chain Nansen does not index → UNVERIFIABLE U-CHAIN, 0 credits", source: "Lookonchain 72956 · 2026-09-18" },
];
